export const downloadChatAsMarkdown = (title, messages) => {
  let content = `# Aethel-Nexus Chat Export\n\n**Export Date:** ${new Date().toLocaleString()}\n\n---\n\n`;
  messages.forEach((msg) => {
    content += `### ${msg.role === 'user' ? 'User' : 'Aethel'}\n${msg.content}\n\n`;
    if (msg.image) content += `*[Image Attached]*\n\n`;
  });
  const element = document.createElement("a");
  const file = new Blob([content], { type: "text/markdown" });
  element.href = URL.createObjectURL(file);
  element.download = `${title.replace(/\s+/g, '_')}_${Date.now()}.md`;
  document.body.appendChild(element); 
  element.click(); 
  document.body.removeChild(element);
};

export const downloadChatAsJSON = (title, messages) => {
  const exportData = { app: "Aethel-Nexus", exportDate: new Date().toISOString(), messages: messages };
  const element = document.createElement("a");
  const file = new Blob([JSON.stringify(exportData, null, 2)], { type: "application/json" });
  element.href = URL.createObjectURL(file);
  element.download = `${title.replace(/\s+/g, '_')}_${Date.now()}.json`;
  document.body.appendChild(element); 
  element.click(); 
  document.body.removeChild(element);
};

export const downloadChatAsPDF = (title, messages) => {
  const printWindow = window.open('', '_blank');
  
  const htmlContent = messages.map(m => {
    // Safely define the regex to avoid markdown parser collisions
    const codeBlockRegex = new RegExp('```([\\s\\S]*?)```', 'g');
    
    let formattedContent = m.content
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/g, '<em>$1</em>')
      .replace(codeBlockRegex, '<pre style="background:#f4f4f4;padding:10px;border-radius:5px;overflow-x:auto;"><code>$1</code></pre>')
      .replace(/\n/g, '<br/>');
      
    return `
      <div style="margin-bottom: 20px; padding: 15px; border-radius: 8px; ${m.role === 'user' ? 'background-color: #f8fafc; border: 1px solid #e2e8f0;' : 'background-color: #ffffff; border: 1px solid #e0e7ff;'}">
        <h4 style="margin-top: 0; color: ${m.role === 'user' ? '#475569' : '#4f46e5'}; font-family: sans-serif; text-transform: uppercase; font-size: 12px; letter-spacing: 1px;">
          ${m.role === 'user' ? 'You' : 'Aethel AI'}
        </h4>
        <div style="font-family: serif; line-height: 1.6; color: #333;">${formattedContent}</div>
      </div>
    `;
  }).join('');

  const htmlTemplate = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        <style>
          body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; color: #0f172a; }
          h1 { text-align: center; color: #1e293b; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; margin-bottom: 30px; }
          @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
        </style>
      </head>
      <body>
        <h1>${title} - Transcript</h1>
        ${htmlContent}
        <div style="text-align: center; margin-top: 40px; font-size: 10px; color: #94a3b8; font-family: sans-serif;">
          Generated by Aethel-Nexus AI Workspace • ${new Date().toLocaleString()}
        </div>
        <script>
          window.onload = () => { window.print(); window.setTimeout(() => window.close(), 500); };
        </script>
      </body>
    </html>
  `;

  printWindow.document.write(htmlTemplate);
  printWindow.document.close();
};